[build-system]
requires = ["setuptools >= 40.6.0", "setuptools-scm", "cython"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target_version = ['py27', 'py34', 'py35', 'py36', 'py37', 'py38']
exclude = '''
(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build/
  | buck-out/
  | build/
  | dist/
  | ddtrace/(
    contrib/
    (
      aiobotocore
      | aiohttp
      | aiopg
      | algoliasearch
      | asyncio
      | boto
      | botocore
      | bottle
      | cassandra
      | celery
      | consul
      | dbapi
      | dogpile_cache
      | elasticsearch
      | falcon
      | flask
      | flask_cache
      | futures
      | gevent
      | grpc/
      (
        __init__.py
        | constants.py
        | patch.py
        | server_interceptor.py
        | utils.py
      )
      | httplib
      | jinja2
      | kombu
      | logging
      | mako
      | molten
      | mongoengine
      | mysql
      | mysqldb
      | psycopg
      | pylibmc
      | pylons
      | pymemcache
      | pymongo
      | pymysql
      | pyramid
      | redis
      | rediscluster
      | requests/
      (
        __init__.py
        | constants.py
        | legacy.py
        | patch.py
        | session.py
      )
      | sqlalchemy
      | sqlite3
      | tornado
      | util.py
      | vertica
    )
    | opentracer/
    | profile/exporter/pprof_pb2.py$
    | vendor/
  )
  | tests/
  (
    contrib/
    (
      aiobotocore
      | aiohttp
      | aiopg
      | algoliasearch
      | asyncio
      | boto
      | botocore
      | bottle
      | cassandra
      | celery
      | config.py
      | consul
      | dbapi
      | elasticsearch
      | falcon
      | flask
      | flask_autopatch
      | flask_cache
      | futures
      | gevent
      | grpc
      | httplib
      | jinja2
      | kombu
      | logging
      | mako
      | molten
      | mongoengine
      | mysql
      | mysqldb
      | patch.py
      | psycopg
      | pylibmc
      | pylons
      | pymemcache
      | pymongo
      | pymysql
      | pyramid/
      (
        app/web.py
        | __init__.py
        | test_pyramid.py
        | test_pyramid_autopatch.py
      )
      | redis
      | rediscluster
      | requests
      | requests_gevent
      | sqlalchemy
      | sqlite3
      | test_utils.py
      | tornado
      | vertica
    )
    | opentracer/
    | profile/_ast_test_file.py
    | vendor
  )
)
'''
